apiVersion: apps/v1
kind: Deployment
metadata:
  name: pose-producer
  namespace: inference
  labels:
    name: pose-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pose-producer
  template:
    metadata:
      namespace: inference
      labels:
        name: pose-producer
    spec:
      # nodeSelector:
      #   gpu-type: RTX
      restartPolicy: Always
      initContainers:
        - name: agency
          image: wildflowerschools/wf-deep-docker:model-agency-v1
          command: ["python", "-m", "agency", "bundle-download", "--name", "YOLOV4_WF_RES152_256x192_WF_YOLOV4", "--version", "v2"]
          volumeMounts:
          - name: data
            mountPath: /data
          envFrom:
            - secretRef:
                name: gpu-client-secrets
          env:
            - name: AGENCY_BUCKET_NAME
              value: "wildflower-tech-model-zoo"
            - name: AGENCY_CACHE_DIR
              value: /data/cache
      containers:
        - name: pose-producer
          image: wildflowerschools/wf-deep-docker:pose-producer-v76
          imagePullPolicy: Always
          volumeMounts:
          - name: data
            mountPath: /data
          envFrom:
            - secretRef:
                name: gpu-client-secrets
          env:
            - name: ALPHAPOSE_CONFIG
              value: /data/cache/versions/YOLOV4_WF_RES152_256x192_WF_YOLOV4/v2/alphapose-wf_res152_256x192.0.2.yolov4.yaml
            - name: ALPHAPOSE_CHECKPOINT
              value: /data/cache/versions/YOLOV4_WF_RES152_256x192_WF_YOLOV4/v2/alphapose-wf_res152_256x192.0.2.yolov4.pth
            - name: ALPHA_POSE_POSEFLOW
              value: "false"
            - name: RABBIT_HOST
              value: rabbitmq-video-queue.inference.svc.cluster.local
            - name: VIDEO_QUEUE_NAME
              value: pose-processing-queue
            - name: LOG_LEVEL
              value: DEBUG
            - name: GPUS
              value: "0"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: HONEYCOMB_BATCH_SIZE
              value: "500"
            - name: PREFETCH_COUNT
              value: "2"
      volumes:
        - name: data
          hostPath:
            path: /data
            type: Directory
