---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  namespace: inference
  name: nsqd-budget
  labels:
    app: nsq
    component: nsqd
spec:
  selector:
    matchLabels:
      app: nsq
      component: nsqd
  minAvailable: 1
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  namespace: inference
  name: nsqlookupd-budget
  labels:
    app: nsq
    component: nsqlookupd
spec:
  selector:
    matchLabels:
      app: nsq
      component: nsqlookupd
  minAvailable: 1
---
apiVersion: v1
kind: Service
metadata:
  name: nsqlookupd
  namespace: inference
  labels:
    app: nsq
spec:
  ports:
  - port: 4160
    targetPort: 4160
    name: tcp
  - port: 4161
    targetPort: 4161
    name: http
  publishNotReadyAddresses: true
  selector:
    app: nsq
    component: nsqlookupd
---
apiVersion: v1
kind: Service
metadata:
  name: nsqd
  namespace: inference
  labels:
    app: nsq
spec:
  ports:
  - port: 4150
    targetPort: 4150
    name: tcp
  - port: 4151
    targetPort: 4151
    name: http
  selector:
    app: nsq
    component: nsqd
---
apiVersion: v1
kind: Service
metadata:
  name: nsqadmin
  namespace: inference
  labels:
    app: nsq
spec:
  ports:
  - port: 4170
    targetPort: 4170
    name: tcp
  - port: 4171
    targetPort: 4171
    name: http
  selector:
    app: nsq
    component: nsqadmin
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nsqlookupd
  namespace: inference
spec:
  serviceName: "nsqlookupd"
  replicas: 1
  selector:
    matchLabels:
      app: nsq
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      namespace: inference
      labels:
        app: nsq
        component: nsqlookupd
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nsq
              - key: component
                operator: In
                values:
                - nsqlookupd
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: nsqlookupd
        image: nsqio/nsq:v1.1.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 30m
            memory: 64Mi
        ports:
        - containerPort: 4160
          name: tcp
        - containerPort: 4161
          name: http
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 2
        command:
          - /nsqlookupd
      terminationGracePeriodSeconds: 5
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nsqd
  namespace: inference
spec:
  serviceName: "nsqd"
  replicas: 1
  selector:
    matchLabels:
      app: nsq
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      namespace: inference
      labels:
        app: nsq
        component: nsqd
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nsq
              - key: component
                operator: In
                values:
                - nsqd
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: nsqd
        image: nsqio/nsq:v1.1.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 30m
            memory: 64Mi
        ports:
        - containerPort: 4150
          name: tcp
        - containerPort: 4151
          name: http
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 2
        volumeMounts:
        - name: datadir
          mountPath: /data
        command:
          - /nsqd
          - -data-path
          - /data
          - -lookupd-tcp-address
          - nsqlookupd-0.nsqlookupd:4160
          - -broadcast-address
          - $(HOSTNAME).nsqd
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      terminationGracePeriodSeconds: 5
      volumes:
      - name: datadir
        hostPath:
          path: /data/nsqd
          type: Directory

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsqadmin
  namespace: inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nsq
  template:
    metadata:
      namespace: inference
      labels:
        app: nsq
        component: nsqadmin
    spec:
      containers:
      - name: nsqadmin
        image: nsqio/nsq:v1.1.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 30m
            memory: 64Mi
        ports:
        - containerPort: 4170
          name: tcp
        - containerPort: 4171
          name: http
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 5
        command:
          - /nsqadmin
          - -lookupd-http-address
          - nsqlookupd-0.nsqlookupd:4161
      terminationGracePeriodSeconds: 5
# ---
# apiVersion: apps/v1
# kind: Ingress
# metadata:
#   name: nsq
#   namespace: inference
# spec:
#   rules:
#     - host: nsq.example.com
#       http:
#         paths:
#         - path: /
#           backend:
#             serviceName: nsqadmin
#             servicePort: 4171
