# requires the operator
# kubectl apply -f "https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rabbit
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbit-pv-0
spec:
  claimRef:
    name: persistence-posebunny-server-0
    namespace: inference
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: rabbit
  local:
    path: /data/hutch/00
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - dudley-dowrong
          - wildflower-tech-gpu-002


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbit-pv-1
spec:
  claimRef:
    name: persistence-posebunny-server-1
    namespace: inference
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: rabbit
  local:
    path: /data/hutch/01
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - dudley-dowrong
          - wildflower-tech-gpu-002


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbit-pv-2
spec:
  claimRef:
    name: persistence-posebunny-server-2
    namespace: inference
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: rabbit
  local:
    path: /data/hutch/02
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - dudley-dowrong
          - wildflower-tech-gpu-002

---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: posebunny
  namespace: inference
spec:
  replicas: 3
  persistence:
    storageClassName: rabbit
    storage: 100Gi
  resources:
    requests:
      cpu: 2000m
      memory: 6Gi
    limits:
      cpu: 3000m
      memory: 8Gi
  rabbitmq:
    additionalConfig: |
      channel_max = 2300
      heartbeat = 30
      vm_memory_high_watermark.absolute = 5G
