---
apiVersion: v1
kind: Namespace
metadata:
  name: tick


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegraf-admin
  namespace: tick

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telegraf-admin
  namespace: tick
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: telegraf-admin
  namespace: tick
